### ISSUE TITLE
[Dev][Screen] - CartScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#10]
# Todo List Cart Screen : 

## UI
 - [x] Components :
	 - [x] Header
         - [x] Flat List show list of items
         - [x] Total Amount Display
         - [
         - [x] Button proceed to order 
- [x] Styles for components

## Handling Logic
- [x] Get List Product from Redux store at put them into Flat List
- [x] Navigate from this to pre order screen
- [x] Calculate total amount and display
