### ISSUE TITLE
[Dev][Screen] - DetailScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#12]
# Todo List Detail Screen : 

## UI
 - [x] Reusable Components :
	 - [x] Header with back to previous button
	 - [x] Action button " Add to cart " with custom style via props
	 - [x] Button with navigation
	 - [x] Modal Display Product Information 
- [x] Styles for components

## Handling Logic
- [x] Dispatch add to cart action when user click "Add To Cart " Icon appeared in modal
- [x] Dispatch add to wish list action when user click "Add To Favorite" Icon appeared in modal
- [x] Take product id from previous screen and display item depend on that id
