### ISSUE TITLE
[Dev][Screen] - FavoriteScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#13]
# Todo List Favorite Screen : 

## UI
 - [x] Components :
	 - [x] Header
         - [x] Flat List show list of items
- [x] Styles for components

## Handling Logic
- [x] User can press to any items to navigate from this to detail product
