### ISSUE TITLE
[Dev][Screen] - FinishOrderScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#14]
# Todo List Finish Reset Password Screen : 

## UI
 - [x] Components 
     - [x] Display animations to notice Create Order Successfully
 - [x] Styles for components

## Handling Logic
- [x] Navigate to HomeScreen when user press on "OK button"
