### ISSUE TITLE
[Dev][Screen] - FinishResetPasswordScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#15]
# Todo List Finish Reset Password Screen : 

## UI
 - [x] Components 
     - [x] Display animations to notice Reset Password Successfully
 - [x] Styles for components

## Handling Logic
- [x] Navigate to LoginScreen when user press on button
