### ISSUE TITLE
[Dev][Screen] - ForgetPasswordScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#16]
# Todo List Forget Password Screen : 

## UI
 - [x] Components :
	 - [x] ForgetRenderField render text input
- [x] Styles for components

## Handling Logic
- [x] Navigate to ResetPasswordScreen when user press on next button
