### ISSUE TITLE
[Dev][Screen] - IntroScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#17]
# Todo List Intro Screen : 

## UI
 - [x] Components :
	 - [x] Header 
	 - [x] Pagination
	 - [x] Slide
	 - [x] SubSlide
- [x] Styles for components

## Handling Logic
- [x] Scroll to next slide with animated
- [x] Navigate to HomeScreen when press let's start
