### ISSUE TITLE
[Dev][Screen] - OrderScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#18]
# Todo List Order Screen : 

## UI
 - [x] Components :
	 - [x] Header contain order steps
         - [x] Display list orders of user
         - [x] Each order will contains : Receiver Name,  Address, Phone Number, Payment Method , Order Items ... 
- [x] Styles for components

## Handling Logic
- [x] Get list order by user from server and put them into Flat List
- [x] Order status will be update automatically by server ( depend on admin )
