### ISSUE TITLE
[Dev][Screen] - PaymentScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#19]
# Todo List Payment Screen : 

## UI
 - [x] Components :
	 - [x] Header contain order steps
         - [x] Payment body contains : select payment options ( COD & CC )
         - [x] Credit Card Input : name, card id , cvc ... 
- [x] Styles for components

## Handling Logic
- [x] Receive summary order from pre order screen and display into flat list
- [x] Post current CC information to Stripe server and receive token ( Add Credit Card )
- [x] Post token to server and also call Stripe charge API from backend to create new payment
- [x] Create new order dispatch an action and post to the database
- [x] Navigate to Finish Order Screen
