### ISSUE TITLE
[Dev][Screen] - PreOrderScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#20]
# Todo List PreOrder Screen : 

## UI
 - [x] Components :
	 - [x] Header contain order steps
	 - [x] Address : Picker select province/city option
	 - [x] Item in summary
	 - [x] Render field for text input . Ex : enter name, address
	 - [x] Summary order that display list of item
	 - [x] Total button for next step
	 - [x] User information form
	 
- [x] Styles for components

## Handling Logic
- [x] Take information from this and send to Payment Screen
- [x] Carry all fields and combine into Redux form
- [x] Counting total passing into PaymentScreen
