### ISSUE TITLE
[Dev][Screen] - ProductScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#21]
# Todo List Product Screen : 

## UI
 - [x] Components :
	 - [x] Header with animated and blur view
	 - [x] Horizontal Item Display
	 - [x] Product Body
	 - [x] Search Input with animated view
- [x] Styles for components

## Handling Logic
- [x] Search products with given keywords from text input
- [x] Display list of products
- [x] Navigate to Product Detail when user press on any Product
