### ISSUE TITLE
[Dev][Screen] - ProfileScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#22]
# Todo List Profile Screen : 

## UI
 - [x] Components :
	 - [x] Upload Button
	 - [x] Profile Picture with Circle Border
	 - [x] Profile Body that display list detail of current user
	 - [x] Edit Button
	 - [x] Resuable Detail Button
	 - [x] Edit Profile Component
- [x] Styles for components
## Handling Logic
- [x] Navigate from Profile to Edit component when user press Edit Icon
- [x] Wrap all fields into Redux Store
- [x] Upload image to server when user press change profile avatar
- [x] Update new information to server when user press update information button
