### ISSUE TITLE
[Dev][Screen] - SignUpScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#24]
# Todo List Signup Screen : 

## UI
 - [x] Resuable Components :
	 - [x] Render Field ( Text Input )
	 - [x] SignUp Form contains : Name, Email, Password, Confirm Password
	 - [x] Button with navigation
- [x] Styles for components
- [x] Add ImageBackground

## Handling Logic
- [x] Create new account (post request to our server )
- [x] Navigation from Signup to Auth ( goBack )
- [x] Wrap all fields into Redux Store
