### ISSUE TITLE
[Dev][Screen] - Auth Screen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#7]
# Todo List Finish Reset Password Screen : 

## UI
 - [x] Components 
     - [x] Display 2 fields: Email & Password 
     - [x] Image Background
     - [x] Register Button via React-native-paper
 - [x] Styles for components

## Handling Logic
- [x] Navigate from Auth Screen to Login Screen
- [x] Navigate from Auth Screen to Signup Screen
