### ISSUE TITLE
[Dev][Screen] - HomeScreen

### ISSUE THREAD

**Issue by TranHyKhang** [giavudangle/rn-pook-book#9]
# Todo List Home Screen : 

## UI
 - [x] Components
	 - [x] Header contains : Menu & Search Icon
	 - [x] Body : carousel to notice to user about sale product
	 - [x] Display products by category 
	 - [x] Float Button
- [x] Styles for components

## Handling Logic
- [x] Get products from server at take into Flat List
- [x] Navigate to Product Detail when user press on any Product
- [x] Navigate to Product Screen when user press button " See more button "
- [x] Navigate to Search Screen when user press Search icon
- [x] Apply lazyload ( api return product by pagination ) (limit & page)
- [x] Display animated in loading progress
- [x] Display list options when user press on Float Button ( Messenger , PhoneCall , Gmail )
